# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import trial_1_pb2 as trial__1__pb2


class AlertStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeMethod = channel.unary_unary(
                '/trial_1.Alert/InvokeMethod',
                request_serializer=trial__1__pb2.function_message.SerializeToString,
                response_deserializer=trial__1__pb2.returnValue.FromString,
                )
        self.CreateInstance = channel.unary_unary(
                '/trial_1.Alert/CreateInstance',
                request_serializer=trial__1__pb2.initMessage.SerializeToString,
                response_deserializer=trial__1__pb2.initReply.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/trial_1.Alert/CreateAccount',
                request_serializer=trial__1__pb2.cred.SerializeToString,
                response_deserializer=trial__1__pb2.void.FromString,
                )
        self.Login = channel.unary_unary(
                '/trial_1.Alert/Login',
                request_serializer=trial__1__pb2.cred.SerializeToString,
                response_deserializer=trial__1__pb2.returnValue.FromString,
                )


class AlertServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InvokeMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeMethod,
                    request_deserializer=trial__1__pb2.function_message.FromString,
                    response_serializer=trial__1__pb2.returnValue.SerializeToString,
            ),
            'CreateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstance,
                    request_deserializer=trial__1__pb2.initMessage.FromString,
                    response_serializer=trial__1__pb2.initReply.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=trial__1__pb2.cred.FromString,
                    response_serializer=trial__1__pb2.void.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=trial__1__pb2.cred.FromString,
                    response_serializer=trial__1__pb2.returnValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trial_1.Alert', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Alert(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InvokeMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trial_1.Alert/InvokeMethod',
            trial__1__pb2.function_message.SerializeToString,
            trial__1__pb2.returnValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trial_1.Alert/CreateInstance',
            trial__1__pb2.initMessage.SerializeToString,
            trial__1__pb2.initReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trial_1.Alert/CreateAccount',
            trial__1__pb2.cred.SerializeToString,
            trial__1__pb2.void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trial_1.Alert/Login',
            trial__1__pb2.cred.SerializeToString,
            trial__1__pb2.returnValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
