# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trial_1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrial_1.proto\x12\x07trial_1\"r\n\x10\x66unction_message\x12\x12\n\x05\x64\x61ta1\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05\x64\x61ta2\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x08\x66unction\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x08\n\x06_data1B\x08\n\x06_data2B\x0b\n\t_function\"\'\n\x0breturnValue\x12\x10\n\x03val\x18\x01 \x01(\x02H\x00\x88\x01\x01\x42\x06\n\x04_val\"\x06\n\x04void2J\n\x05\x41lert\x12\x41\n\x0cInvokeMethod\x12\x19.trial_1.function_message\x1a\x14.trial_1.returnValue\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trial_1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FUNCTION_MESSAGE']._serialized_start=26
  _globals['_FUNCTION_MESSAGE']._serialized_end=140
  _globals['_RETURNVALUE']._serialized_start=142
  _globals['_RETURNVALUE']._serialized_end=181
  _globals['_VOID']._serialized_start=183
  _globals['_VOID']._serialized_end=189
  _globals['_ALERT']._serialized_start=191
  _globals['_ALERT']._serialized_end=265
# @@protoc_insertion_point(module_scope)
