# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import trial_1_pb2 as trial__1__pb2


class AlertStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeMethod = channel.unary_unary(
                '/trial_1.Alert/InvokeMethod',
                request_serializer=trial__1__pb2.function_message.SerializeToString,
                response_deserializer=trial__1__pb2.returnValue.FromString,
                )


class AlertServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InvokeMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeMethod,
                    request_deserializer=trial__1__pb2.function_message.FromString,
                    response_serializer=trial__1__pb2.returnValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trial_1.Alert', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Alert(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InvokeMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trial_1.Alert/InvokeMethod',
            trial__1__pb2.function_message.SerializeToString,
            trial__1__pb2.returnValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
